id: A1CFDF184
base_file: f0904.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:22:07.207853
  last_modified_at: 2022-06-17 12:22:07.207861
