id: A1CFDF184
base_file: f5A21.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:22:07.212749
  last_modified_at: 2022-06-17 12:22:07.212752
