id: A1CFDF184
base_file: f47C2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:22:07.211678
  last_modified_at: 2022-06-17 12:22:07.211681
